import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

const EXPECTED_NOTEBOOK_SHA='5abff78b9b10a13792b6d1b6cd24df780a64d16b7ec891d2ed74628dbb0b910b';
const EXPECTED_SOURCE_ZIP_SHA='ce3623b87ca221a52bcf886836070ebaebc490cf7574f6f3ce4db78095a32cde';
const INCIDENT_REPAIR='NIH_MOUNT_PACKAGING_V2';
function sha256(data){return crypto.createHash('sha256').update(data).digest('hex');}
function fail(m){throw new Error(m);}
const [artifactDirArg,templateArg,payloadArg,metadataArg]=process.argv.slice(2);
if(!artifactDirArg||!templateArg||!payloadArg||!metadataArg) fail('usage: node v622_build_external_validation_payload.mjs <artifact_dir> <template.py> <payload.ts> <metadata.json>');
const artifactDir=path.resolve(artifactDirArg), notebookPath=path.join(artifactDir,'w16-kernel.ipynb'), templatePath=path.resolve(templateArg), payloadPath=path.resolve(payloadArg), metadataPath=path.resolve(metadataArg);
const notebookBytes=fs.readFileSync(notebookPath); const notebookSha=sha256(notebookBytes); if(notebookSha!==EXPECTED_NOTEBOOK_SHA) fail(`W16 notebook SHA drift: ${notebookSha}`);
const notebook=JSON.parse(notebookBytes.toString('utf8')); const code=(notebook.cells??[]).filter(c=>c&&c.cell_type==='code').map(c=>Array.isArray(c.source)?c.source.join(''):String(c.source??'')).join('\n');
const match=code.match(/ARCHIVE_B64\s*=\s*['\"]([A-Za-z0-9+/=]+)['\"]/s); if(!match) fail('ARCHIVE_B64 not found in recovered W16 source');
const sourceZip=Buffer.from(match[1],'base64'); const sourceZipSha=sha256(sourceZip); if(sourceZipSha!==EXPECTED_SOURCE_ZIP_SHA) fail(`W16 source archive SHA drift: ${sourceZipSha}`);
let script=fs.readFileSync(templatePath,'utf8');
if(!script.includes('__SOURCE_ZIP_B64__')) fail('external template source placeholder missing');
script=script.replaceAll('__SOURCE_ZIP_B64__',sourceZip.toString('base64'));
if(script.includes('__SOURCE_ZIP_B64__')) fail('external template replacement incomplete');

const oldNih=`nih_labels=next(iter(sorted(INPUT.rglob('sample_labels.csv'))),None)\nnih_zip=next(iter(sorted(INPUT.rglob('sample.zip'))),None)\nif nih_labels is None or nih_zip is None: raise RuntimeError('NIH sample labels/zip not found in Kaggle mounts')\nnih_extract=WORK/'nih_sample_images'; nih_extract.mkdir(exist_ok=True)\nwith zipfile.ZipFile(nih_zip) as z: z.extractall(nih_extract)\nnih_raw=pd.read_csv(nih_labels)\nrequired={'Image Index','Finding Labels'}\nif not required.issubset(nih_raw.columns): raise RuntimeError(f'NIH sample columns missing: {sorted(required-set(nih_raw.columns))}')\nindex={p.name:p.resolve() for p in nih_extract.rglob('*') if p.is_file() and p.suffix.lower() in image_ext}`;
const newNih=`nih_label_candidates=sorted(INPUT.rglob('sample_labels.csv'),key=lambda p:(0 if 'nih' in str(p).lower() else 1,len(p.parts),str(p)))\nnih_labels=None; nih_raw=None\nrequired={'Image Index','Finding Labels'}\nfor candidate in nih_label_candidates:\n    try: candidate_frame=pd.read_csv(candidate)\n    except Exception: continue\n    if required.issubset(candidate_frame.columns):\n        nih_labels=candidate.resolve(); nih_raw=candidate_frame; break\nif nih_labels is None or nih_raw is None: raise RuntimeError('NIH sample_labels.csv with required columns not found in Kaggle mounts')\ntry:\n    rel=nih_labels.relative_to(INPUT.resolve())\nexcept ValueError:\n    rel=nih_labels.resolve().relative_to(INPUT.resolve())\nif not rel.parts: raise RuntimeError('NIH labels mount root cannot be resolved')\nnih_mount_root=(INPUT/rel.parts[0]).resolve()\nnih_zip_candidates=sorted(nih_mount_root.rglob('sample.zip'))\nnih_packaging='mounted_directory'\nif nih_zip_candidates:\n    nih_zip=nih_zip_candidates[0]\n    nih_image_root=WORK/'nih_sample_images'; nih_image_root.mkdir(exist_ok=True)\n    with zipfile.ZipFile(nih_zip) as z: z.extractall(nih_image_root)\n    nih_packaging='zip'\nelse:\n    preferred=[nih_mount_root/'sample',nih_mount_root/'images',nih_mount_root]\n    nih_image_root=next((p for p in preferred if p.is_dir() and any(q.is_file() and q.suffix.lower() in image_ext for q in p.rglob('*'))),None)\n    if nih_image_root is None: raise RuntimeError(f'NIH images not found under mounted dataset root {nih_mount_root}')\nimage_paths=sorted(p.resolve() for p in nih_image_root.rglob('*') if p.is_file() and p.suffix.lower() in image_ext)\nif not image_paths: raise RuntimeError('NIH image discovery produced zero files')\nindex={}; duplicates=set()\nfor p in image_paths:\n    if p.name in index and index[p.name]!=p: duplicates.add(p.name)\n    else: index[p.name]=p\nif duplicates: raise RuntimeError(f'NIH duplicate image basenames: {sorted(duplicates)[:10]}')\nprint(json.dumps({'stage':'NIH_MOUNT_DISCOVERY','repair':'NIH_MOUNT_PACKAGING_V2','packaging':nih_packaging,'mount_root':str(nih_mount_root),'image_root':str(nih_image_root),'images_discovered':len(index),'labels_csv':str(nih_labels)},sort_keys=True))`;
if(!script.includes(oldNih)) fail('expected v1 NIH packaging block not found; refusing unscoped repair');
if(script.indexOf(oldNih)!==script.lastIndexOf(oldNih)) fail('v1 NIH packaging block is not unique');
script=script.replace(oldNih,newNih);
const oldReport="nih_load_report={'name':'nih_pneumonia_vs_no_finding','adapter':'nih_sample','root':str(nih_zip.parent),'manifest_csv':str(nih_labels),'n_images':int(len(nih_frame)),'n_patients':int(nih_frame['patient_id'].nunique()),'class_counts':{str(k):int(v) for k,v in nih_frame['label'].value_counts().sort_index().to_dict().items()},'site_counts':{'nih':int(len(nih_frame))},'has_real_patient_metadata':bool((nih_frame['patient_id_source']=='dataset_metadata').any()),'task_definition':'Pneumonia-containing vs No Finding only','label_policy':{'nih_positive_policy':'contains_pneumonia','nih_negative_policy':'no_finding_only'}}";
const newReport="nih_load_report={'name':'nih_pneumonia_vs_no_finding','adapter':'nih_sample','root':str(nih_mount_root),'manifest_csv':str(nih_labels),'packaging':nih_packaging,'discovered_image_count':int(len(index)),'incident_repair':'NIH_MOUNT_PACKAGING_V2','n_images':int(len(nih_frame)),'n_patients':int(nih_frame['patient_id'].nunique()),'class_counts':{str(k):int(v) for k,v in nih_frame['label'].value_counts().sort_index().to_dict().items()},'site_counts':{'nih':int(len(nih_frame))},'has_real_patient_metadata':bool((nih_frame['patient_id_source']=='dataset_metadata').any()),'task_definition':'Pneumonia-containing vs No Finding only','label_policy':{'nih_positive_policy':'contains_pneumonia','nih_negative_policy':'no_finding_only'}}";
if(!script.includes(oldReport)) fail('expected v1 NIH load-report block not found');
script=script.replace(oldReport,newReport);
const oldSummary="'external_results_feed_back_forbidden':True,'validated_at'";
const newSummary="'external_results_feed_back_forbidden':True,'incident_repair':'NIH_MOUNT_PACKAGING_V2','prior_failed_kernel_version':1,'repair_scope':'NIH input packaging discovery only; frozen model/policy unchanged','validated_at'";
if(!script.includes(oldSummary)) fail('external summary repair insertion point missing');
script=script.replace(oldSummary,newSummary);

const scriptSha=sha256(Buffer.from(script,'utf8')); fs.mkdirSync(path.dirname(payloadPath),{recursive:true});
fs.writeFileSync(payloadPath,`// Generated only on trusted runner from recovered W16 source. Do not commit.\nexport const EXTERNAL_VALIDATION_SCRIPT=${JSON.stringify(script)} as const;\nexport const EXTERNAL_VALIDATION_SCRIPT_SHA256=${JSON.stringify(scriptSha)} as const;\nexport const W16_NOTEBOOK_SHA256=${JSON.stringify(notebookSha)} as const;\nexport const W16_SOURCE_ZIP_SHA256=${JSON.stringify(sourceZipSha)} as const;\n`,'utf8');
const metadata={project:'PNEUMONIA V6.2.2',stage:'EXTERNAL_VALIDATION_PAYLOAD_BUILD',incident_repair:INCIDENT_REPAIR,prior_failed_kernel_version:1,repair_scope:'NIH input packaging discovery only; frozen model/policy unchanged',w16_notebook_sha256:notebookSha,w16_source_zip_sha256:sourceZipSha,final_freeze_manifest_sha256:'2313023819c9eec669d835b99dcc2524b03bb0da236c2ec8f98c4e1221948414',reconciliation_sha256:'99a319c8d397342aaefd3c15e0eb8f968a973738f55ef97925a2a16da8c485d8',official_locked_test_completion_sha256:'2ecc67f4268f812604e51db5b46d2ece36f9de12ff7baf3cf0bbbc8df4a58ada',external_validation_script_sha256:scriptSha,cohorts:['ashery/chexpert','nih-chest-xrays/sample'],training_hpo_confirmation_reselection:false};
fs.writeFileSync(metadataPath,JSON.stringify(metadata,null,2)+'\n','utf8'); console.log(JSON.stringify(metadata,null,2));
