import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

const [sourceDirArg, templateArg, outputArg] = process.argv.slice(2);
if (!sourceDirArg || !templateArg || !outputArg) {
  throw new Error('usage: node scripts/v623_build_p0_payload.mjs <source-artifact-dir> <template.py> <output.ts>');
}

const EXPECTED_NOTEBOOK_SHA = '5abff78b9b10a13792b6d1b6cd24df780a64d16b7ec891d2ed74628dbb0b910b';
const EXPECTED_SOURCE_ZIP_SHA = 'ce3623b87ca221a52bcf886836070ebaebc490cf7574f6f3ce4db78095a32cde';
const PLACEHOLDER = '__SOURCE_ZIP_B64__';
const sha256 = (value) => crypto.createHash('sha256').update(value).digest('hex');

const notebookPath = path.join(sourceDirArg, 'w16-kernel.ipynb');
if (!fs.existsSync(notebookPath)) throw new Error(`missing recovered notebook: ${notebookPath}`);
const notebookBytes = fs.readFileSync(notebookPath);
const notebookSha = sha256(notebookBytes);
if (notebookSha !== EXPECTED_NOTEBOOK_SHA) throw new Error(`W16 notebook SHA drift: ${notebookSha}`);

const notebook = JSON.parse(notebookBytes.toString('utf8'));
const code = (notebook.cells ?? [])
  .filter((cell) => cell && cell.cell_type === 'code')
  .map((cell) => Array.isArray(cell.source) ? cell.source.join('') : String(cell.source ?? ''))
  .join('\n');
const match = code.match(/ARCHIVE_B64\s*=\s*['"]([A-Za-z0-9+/=]+)['"]/s);
if (!match) throw new Error('ARCHIVE_B64 not found in recovered W16 source');
const sourceZipBytes = Buffer.from(match[1], 'base64');
const sourceZipSha = sha256(sourceZipBytes);
if (sourceZipSha !== EXPECTED_SOURCE_ZIP_SHA) throw new Error(`W16 source ZIP SHA drift: ${sourceZipSha}`);

const template = fs.readFileSync(templateArg, 'utf8');
if ((template.split(PLACEHOLDER).length - 1) !== 1) throw new Error('P0 template source placeholder cardinality mismatch');
const script = template.replace(PLACEHOLDER, sourceZipBytes.toString('base64'));
if (script.includes(PLACEHOLDER)) throw new Error('P0 template replacement incomplete');
const scriptSha = sha256(Buffer.from(script, 'utf8'));

const githubRunId = String(process.env.GITHUB_RUN_ID ?? '').trim();
if (!/^\d+$/.test(githubRunId)) throw new Error('GITHUB_RUN_ID missing or invalid');
const expiresAtMs = Date.now() + 6 * 60 * 60 * 1000;

const out = [
  '// GENERATED BY scripts/v623_build_p0_payload.mjs — DO NOT COMMIT GENERATED CONTENT',
  `export const P0_SCRIPT: string = ${JSON.stringify(script)};`,
  `export const P0_SCRIPT_SHA256: string = ${JSON.stringify(scriptSha)};`,
  `export const W16_NOTEBOOK_SHA256: string = ${JSON.stringify(notebookSha)};`,
  `export const W16_SOURCE_ZIP_SHA256: string = ${JSON.stringify(sourceZipSha)};`,
  `export const P0_GITHUB_RUN_ID: string = ${JSON.stringify(githubRunId)};`,
  `export const P0_EXPIRES_AT_MS: number = ${expiresAtMs};`,
  '',
].join('\n');
fs.writeFileSync(outputArg, out, 'utf8');
console.log(JSON.stringify({
  p0_payload: 'PASS',
  script_sha256: scriptSha,
  w16_notebook_sha256: notebookSha,
  w16_source_zip_sha256: sourceZipSha,
  github_run_id: githubRunId,
  expires_at_ms: expiresAtMs,
}));
